<a href="https://colab.research.google.com/github/fernandovidalnn/Colab-Mineria-de-datos/blob/main/clase_git_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [5]:
# Carga de datos
data_frame = pd.read_csv("Churn_Modelling.csv")
data_frame.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
 # Valores nulos
for feature in data_frame.columns:
  print('Total de valores nulos de', feature, '=', data_frame[feature].isna().sum())

Total de valores nulos de RowNumber = 0
Total de valores nulos de CustomerId = 0
Total de valores nulos de Surname = 0
Total de valores nulos de CreditScore = 0
Total de valores nulos de Geography = 0
Total de valores nulos de Gender = 0
Total de valores nulos de Age = 0
Total de valores nulos de Tenure = 0
Total de valores nulos de Balance = 0
Total de valores nulos de NumOfProducts = 0
Total de valores nulos de HasCrCard = 0
Total de valores nulos de IsActiveMember = 0
Total de valores nulos de EstimatedSalary = 0
Total de valores nulos de Exited = 0

In [8]:
# Selecciona solo las características que se van a considerar en los,posteriores análisis
X = data_frame.iloc[:, 3:-1].values
# La ùltima columna (sale o no sale) se separa del resto para analizar la, relación que tiene ella con el resto
y = data_frame.iloc[:, -1].values

In [10]:
pd.DataFrame(X).head(10)

     0        1       2   3  4          5  6  7  8          9
0  619   France  Female  42  2        0.0  1  1  1  101348.88
1  608    Spain  Female  41  1   83807.86  1  0  1  112542.58
2  502   France  Female  42  8   159660.8  3  1  0  113931.57
3  699   France  Female  39  1        0.0  2  0  0   93826.63
4  850    Spain  Female  43  2  125510.82  1  1  1    79084.1
5  645    Spain    Male  44  8  113755.78  2  1  0  149756.71
6  822   France    Male  50  7        0.0  2  1  1    10062.8
7  376  Germany  Female  29  4  115046.74  4  1  0  119346.88
8  501   France    Male  44  4  142051.07  2  0  1    74940.5
9  684   France    Male  27  2  134603.88  1  1  1   71725.73

In [11]:
pd.DataFrame(y).head(5)

   0
0  1
1  0
2  1
3  0
4  0

# Transformación de variables categóricas

In [14]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['frio', 'frio', 'templado', 'frio', 'calor', 'calor', 'templado','frio', 'templado', 'calor']
values = array(data)
print('Valores:',values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print('Label encoder integer:',integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print('one-hot encoder:\n', onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

Valores: ['frio' 'frio' 'templado' 'frio' 'calor' 'calor' 'templado' 'frio'
 'templado' 'calor']
Label encoder integer: [1 1 2 1 0 0 2 1 2 0]
one-hot encoder:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
['frio']

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
pd.DataFrame(X)

        0        1  2   3   4          5  6  7  8          9
0     619   France  0  42   2        0.0  1  1  1  101348.88
1     608    Spain  0  41   1   83807.86  1  0  1  112542.58
2     502   France  0  42   8   159660.8  3  1  0  113931.57
3     699   France  0  39   1        0.0  2  0  0   93826.63
4     850    Spain  0  43   2  125510.82  1  1  1    79084.1
...   ...      ... ..  ..  ..        ... .. .. ..        ...
9995  771   France  1  39   5        0.0  2  1  0   96270.64
9996  516   France  1  35  10   57369.61  1  1  1  101699.77
9997  709   France  0  36   7        0.0  1  0  1   42085.58
9998  772  Germany  1  42   3   75075.31  2  1  0   92888.52
9999  792   France  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [17]:
# Primero se revisan los valores únicos
pd.DataFrame(X)[1].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
pd.DataFrame(X)

       0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_data = sc.fit_transform(X)
pd.DataFrame(scaled_data).head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276